blank_issues_enabled: true
contact_links:
  - name: Security Experts Community Support
    url: https://github.com/orgs/Security-Experts-Community/discussions
    about: Please ask and answer questions here.
